[workspace]
name = "conda-ros"
channels = ["conda-forge"]
platforms = ["linux-64"]

[dependencies]
python = ">=3.11"
pyyaml = "*"
rattler-build = "*"

[tasks]
generate-recipes = "python -m pipeline.generate_recipes"
generate-build-config = "python -m pipeline.generate_build_config"
resolve-build-order = "python -m pipeline.resolve_build_order"
run-build = "python -m pipeline.run_build"
